<div class="page-heading">				
  <h2 class="page-title">
    <i class="icon-user"></i> Conselho de Presidentes -ADMIN-
  </h2>					
  <div class="page-info hidden-xs">
    <ul class="stats">
      <li>
        <span id="Membros" class="large text-warning"></span>
        <span class="mini">Membros</span>
      </li>
      <li>
        <span id="Mensagens" class="large text-info"></span>
        <span class="mini">Mensagens</span>
      </li>
      <li>
        <span id="Perguntas" class="large text-success"></span>
        <span class="mini">Perguntas</span>
      </li>
      <li>
        <span id="Respostas" class="large text-danger"></span>
        <span class="mini">Respostas</span>
      </li>
      <li>
        <a href="/admin/auth/logout">
          <span class="large text-info"><i class="fa fa-sign-out"></i></span>
          <span class="mini">Sair</span>
        </a>
      </li>
    </ul>
  </div>
</div>
